version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
volumes:
  postgres_data:
